notifications:
  email:
    - philippe.delrieu@free.fr
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libportmidi-dev
script:
  - rustpkg build portmidi
  - rustdoc -o ./doc ./src/portmidi/lib.rs


