env:
  global:
    - secure: TeiN4v6xNRQYOX8ahW9XYftnxfLVUw3e3M9PmfxHk6UPLZmPXAeOYXjT9yDP86cnErwslxPbE33d/O8zzOexbfDY/kEgo5nfP979Zx58BS2GgeudPsVVpWn7X2KbnvocC2cHIkJJt4Xoe+BgMisQvN1Cgc7AblnDdA84JPAyE3M=
notifications:
  email:
    - philippe.delrieu@free.fr
install:
  - sudo apt-get install libportmidi-dev
language: rust
script:
  - cargo build
os:
  - linux


